#WebApi Build
name: ' webapi build'
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select env:- Dev/QA/Prod'
        required: true

jobs:
  Build-and-Deploy:
    runs-on: windows-latest
    env:
      #DOTNET_VERSION: '6.0.100'
      SOLUTIONPATH: '.sln'
    steps:

 #Checkout  repository

    - name: 'Checkout GitHub Code'
      uses: actions/checkout@v2

 #Checkout  repository

    #- name: 'Checkout repo'
     # uses: actions/checkout@v2
      #with:
       # repository:
        #token: ${{  }}
        #path:

  #Setup dotnet

    - name: Setup DotNet ${{ env.DOTNET_VERSION }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

  #Build code
    - name: Build code
      run: dotnet build ${{env.SOLUTIONPATH}} --configuration Release

     
  #Make Dir
    - name: make directory for test
      run: mkdir -p testdir

  #Run unit test
    - name: Run unit test
      run: dotnet test  ${{ env.SOLUTIONPATH }} --logger html --results-directory testdir --no-build

  #upload artifacts
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: Upload artifacts
        path: testdir 
